### ISSUE TITLE
Workspace Combobox

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#10]
Need some intuitive way to both display what workspace you are in, and to be able to switch workspaces. Maybe a [shadcn/ui combobox](https://ui.shadcn.com/docs/components/combobox)

**Comment by manstephen** [comment]
Combobox lists all user spaces and allows user to redirect to each workspace.
TODO:
1. Fix current workspace selection bug
2. Check that new workspace is added to combobox when a new workspace is created
