### ISSUE TITLE
Clicking on a campaign should default to going into the calling interface. Then let there be a settings button on the row that goes to the /campaigns/$id page

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#102]
Since there are more callers then there are admins, default behaviour for the /workspaces/$id/campaigns table should be that clicking a campaign should take you to the most desired page (the calling interface: /workspaces/$id/campaigns/$id/call). Then a gear icon on the row can take admins to the /workspaces/$id/campaigns/$id page

**Comment by sai-sy** [comment]
Did this get implemented? I think I’m acc backpedaling on this decision. A
dedicated join campaign button is nice and a better indicator on what’s
happening to a user

---
Thanks!
He/Him
Saihaan "Sai" Syed

**Comment by wra-sol** [comment]
Left it as is Sent from my iPhoneOn Aug 22, 2024, at 3:21 PM, Sai ***@***.***> wrote:﻿
Did this get implemented? I think I’m acc backpedaling on this decision. A

dedicated join campaign button is nice and a better indicator on what’s

happening to a user



---

Thanks!

He/Him

Saihaan "Sai" Syed
