### ISSUE TITLE
Campaign creation should include creating the type. and the type should be immutable

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#176]
ask @wra-sol before making changes to that dashboard page. His questionnaire builder will cause merge conflicts

**Comment by manstephen** [comment]
Make the campaign type dropdown in campaign settings into text @manstephen

**Comment by sai-sy** [comment]
Some sort of label or even aesthetic way to show the type of campaign in both /campaigns/$id and /campaigns/$id/settings
