### ISSUE TITLE
power dialer connects a call then hangs up after a certain amount of time

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#187]

**Comment by wra-sol** [comment]
Need more details on scenarios here. If we can write down numbers where this happens, I can look in Twilio analytics.

**Comment by sai-sy** [comment]
Due to the glitch with the caller UI, I was unable to get them to take down who it happened with. Regarding when: I just have a list of time stamps without notes beside them so that's on me.
