### ISSUE TITLE
Disposition shouldn't be part of the qustionnaire

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#198]
Disposition is necessary and should in the contact area
Also less options, ANSWER, NO ANSWER are enough options. 
design in a way that in the future we can implement: workspace managers can add more dispositions and decide 1. which dispositions do they retry on and 2. how many times
SCHEDULED CALLBACK should also eventually be a default disposition

**Comment by wra-sol** [comment]
This is bigger lift. I get what you're saying but for now we should keep it in the results.

**Comment by sai-sy** [comment]
moving it off of the demo MVP but keeping it open
