### ISSUE TITLE
no script shouldn't app error. should just prompt

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#357]

**Comment by sai-sy** [comment]
parthiv says he can join the campaign and make dials. he shouldn't be able to without a script. It should prompt saying "this live call campaign doesn't have a script. Please contact an administrator to load a script"

**Comment by wra-sol** [comment]
Require a script? I don't think we should.

**Comment by sai-sy** [comment]
It's a flow thing. Yes there are cases where you want an extra script, but there are more cases where you forgot to put a script and need a prompt or a wall to remind you. If you want an empty script organizers know to throw in a blank notes box.
