### ISSUE TITLE
predictive dialer seems to move on without giving the caller time to enter information

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#422]

**Comment by wra-sol** [comment]
I can implement a wait, or wait for submit to continue dialing. The balance here is tough.

**Comment by wra-sol** [comment]
Closed on #440

**Comment by sai-sy** [comment]
not sure what you did, but definitely a wait for submit. The interface shouldn't move on if a person takes a while to fill out the form or happens to just getup from their desk after a call
