### ISSUE TITLE
Draft Status for Campaigns

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#45]
Campaigns could have a draft status so you don't lose your work if you're creating a campaign. This is a big issue with other software

**Comment by sai-sy** [comment]
@wra-sol could you elaborate on this, cause from FE I see no diff

**Comment by wra-sol** [comment]
There is now a "Draft" in the campaign status drop down. This will make it invisible to callers and members, visible to owners and managers.

**Comment by sai-sy** [comment]
currently, the status drop-down for me doesn't show draft mode and that drop-down is blank on campaign creation.

On campaign creation, campaigns should be in draft until made complete and "started"

rather then a drop down deep in the settings, a more clear indication of whether a campaign is started or stopped or in draft (paused) might be better.
