### ISSUE TITLE
/workspaces/$id frontend

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#50]

**Comment by manstephen** [comment]
Okay I finally figured out a method for getting the campaign's completion progress. Here's the first pass: 

![Image](https://github.com/chester-hill-solutions/callcaster/assets/56130056/607796ad-493d-4b33-a589-4a0ccd62eb13)

And you can currently just download the raw data from the table as a CSV which looks like this: 

![Image](https://github.com/chester-hill-solutions/callcaster/assets/56130056/e2bb09af-44b6-459c-9610-ec864147d4f2)

We'll definitely need to test and optimize this for but for now it works.
