### ISSUE TITLE
"Voicemail left" displaying when not supposed to

### ISSUE THREAD

**Issue by camerongiles** [chester-hill-solutions/callcaster#629]
After hanging up on a completed call, the disposition automatically selected "Voicemail left" even though the call connected.
<img width="1710" alt="Screenshot 2024-09-11 at 6 15 11 PM" src="https://github.com/user-attachments/assets/7b08064a-1115-4e74-851f-8411c97db007">

**Comment by wra-sol** [comment]
Looking at the twilio log of the call, it's showing that it was answered by the machine. Which will always send this status. Did a human pick up?
