### ISSUE TITLE
Workspace "Three" [ 6aff2ab3-8a7a-48b2-92e6-f86ec7441ca0 ] is too antiquated and throws an error when trying to access the settings page to delist the phone #s, so they'll need to be removed manually

### ISSUE THREAD

**Issue by manstephen** [chester-hill-solutions/callcaster#674]
Workspace "Three" [ 6aff2ab3-8a7a-48b2-92e6-f86ec7441ca0 ] is too antiquated and throws an error when trying to access the settings page to delist the phone #s, so they'll need to be removed manually

![image](https://github.com/user-attachments/assets/3d7bea21-2c6e-4688-8161-c3800bea2aa5)

_Originally posted by @manstephen in https://github.com/chester-hill-solutions/callcaster/issues/635#issuecomment-2365312872_

**Comment by manstephen** [comment]
Workspace "TSP" `14b73d6e-3e0a-42c8-b8b8-5c536e4cd626`: 
![image](https://github.com/user-attachments/assets/cf652eaa-627c-40d6-a16d-83f396b7775d)

**Comment by manstephen** [comment]
Workspace "NJA Test" `d459e3e7-b739-47e2-a85c-debe3268796f`:
![image](https://github.com/user-attachments/assets/de61fe96-958e-4101-8947-c876c1861460)

**Comment by wra-sol** [comment]
These numbers are deleted
