### ISSUE TITLE
Email invite for new accounts doesn't correctly send the user to a sign-up page

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#688]

**Comment by parthiv-2006** [comment]
After clicking on the "Get Started" button from the email sent to a new unregistered account I was sent to this page: 

Email I received:
![Image](https://github.com/user-attachments/assets/99c1c48a-7021-41b4-a81b-8b5ba950e6da)

Error page:
![Image](https://github.com/user-attachments/assets/23b7d19a-1e97-45e9-b959-fda76a992a57)

**Comment by sai-sy** [comment]
this only works on prod. test it there and move it
