### ISSUE TITLE
Caller faced this while calling for tanveer

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#705]
![Untitled](https://github.com/user-attachments/assets/73b52060-4d75-490d-9623-d779c285713d)

**Comment by wra-sol** [comment]
When?

**Comment by sai-sy** [comment]
Last night, didn't send error report just send tanveer this picture

**Comment by wra-sol** [comment]
Why wouldn’t they send the report lmao

Nathaniel Arfin
***@***.***
905-808-8017
