### ISSUE TITLE
Login Box Doesn't Scale Correctly with Screen Size Scaling

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#88]
Conditions:
- Fixfox
- 1920 x 1080
- 150% Screen Scaling

![image](https://github.com/chester-hill-solutions/callcaster/assets/74868837/8ce6b52d-79ba-42cd-81ca-b611a6c8f62a)

**Comment by manstephen** [comment]
Fixed in PR #89, I was scaling the card using height:100vh, making it scale with the size of the entire screen when I should've had it scale with height:100%.
