### ISSUE TITLE
hangup vs smart drop vs drop voicemail

### ISSUE THREAD

**Issue by sai-sy** [chester-hill-solutions/callcaster#95]
there should be a choice to "smart drop" a voicemail or just hangup. Do those buttons show up for the caller.

**Comment by parthiv-2006** [comment]
I don't see this

**Comment by wra-sol** [comment]
Feature flags. Gimme the workspace and I’ll turn it on.Sent from my iPhoneOn Sep 13, 2024, at 6:50 PM, parthiv-2006 ***@***.***> wrote:﻿
Reopened #95.

**Comment by sai-sy** [comment]
turn it on for 24-25 tanveer shahnawaz campaign and callcaster testing
workspace and 2024 BEY outreach

---
Thanks!
He/Him
Saihaan "Sai" Syed

**Comment by sai-sy** [comment]
do feature flags affect prod? or no feature flags themselves r only on
hearty?

---
Thanks!
He/Him
Saihaan "Sai" Syed

**Comment by wra-sol** [comment]
Only on hearty.Sent from my iPhoneOn Sep 13, 2024, at 7:28 PM, Sai ***@***.***> wrote:﻿
do feature flags affect prod? or no feature flags themselves r only on

hearty?



---

Thanks!

He/Him

Saihaan "Sai" Syed





On Fri, Sep 13, 2024 at 7:27 PM Saihaan Syed ***@***.***>

wrote:



> turn it on for 24-25 tanveer shahnawaz campaign and callcaster testing

> workspace and 2024 BEY outreach

>

> ---

> Thanks!

> He/Him

> Saihaan "Sai" Syed

>

>

**Comment by sai-sy** [comment]
it that true across the board? or just because feature flags haven’t been
pushed either

**Comment by wra-sol** [comment]
Yeah, if you run a branch diff on Prod and Master, the feature list is massive.Also I’m now seeing the need to improve my PR conventions.Sent from my iPhoneOn Sep 13, 2024, at 7:38 PM, Sai ***@***.***> wrote:﻿
it that true across the board? or just because feature flags haven’t been

pushed either

**Comment by sai-sy** [comment]
turn everyone on for CallCaster Tester and 24 BEY Outreach. Gonna get the
kids to test all of them and move them into clear for prod

For example some invite problems tonight

---
Thanks!
He/Him
Saihaan "Sai" Syed

**Comment by parthiv-2006** [comment]
@wra-sol "audio drop" button doesn't seem to work. When the button is pressed the call continues to say connected and there's also no visual indicator that the button was pressed unlike the "hang up" and "start" buttons.
